# Black settings (code formatter)
[tool.black]
line-length = 120
target-version = ["py313"]
skip-string-normalization = true  # Disables automatic quote normalization

# isort settings (import sorting)
[tool.isort]
line_length = 120
profile = "black"
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true
combine_as_imports = true
known_first_party = ["backend", "users"]

# Ruff settings (linter)
[tool.ruff]
line-length = 120
target-version = "py313"
fix = true
lint.select = ["E", "F", "W", "I"]
lint.ignore = ["E203"]
exclude = ["migrations"]


# Pytest settings
[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "Wishlist.settings"
python_files = ["test_*.py"]
pytest_plugins = ["pytest_mock"]
testpaths = ["tests"]
addopts = "-ra --strict-markers --disable-warnings"


# Pre-commit settings (pre-commit hooks)
[tool.pre-commit]
repos = [
    { repo = "https://github.com/psf/black", rev = "25.1.0", hooks = [{ id = "black" }] },
    { repo = "https://github.com/pycqa/isort", rev = "6.0.1", hooks = [{ id = "isort" }] },
    { repo = "https://github.com/charliermarsh/ruff-pre-commit", rev = "0.9.10", hooks = [{ id = "ruff" }] }
]
