name: Docker Compose CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /${{ secrets.SSH_USER }}
            rm -rf wishlist
            git clone git@github.com:${{ github.repository }}.git wishlist
            cd wishlist
            echo "${{ secrets.ENV_FILE_PROD }}" > wishlist/prod.env
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build
